-- 코드를 작성해주세요
SELECT THREE.ID AS ID
FROM ECOLI_DATA AS ONE
INNER JOIN ECOLI_DATA AS TWO ON ONE.ID = TWO.PARENT_ID
INNER JOIN ECOLI_DATA AS THREE ON TWO.ID = THREE.PARENT_ID
WHERE ONE.PARENT_ID IS NULL;