-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, 
    (30 * C.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND D.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
          SELECT 1
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
          WHERE R.CAR_ID = C.CAR_ID
            AND R.START_DATE <= '2022-11-30'
            AND R.END_DATE >= '2022-11-01'
      )
) AS T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;