-- 코드를 작성해주세요
WITH RECURSIVE GENERATIONS AS (
    -- 부모가 없는 개체: 1세대
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 이전 세대의 자식: 세대 + 1
    SELECT C.ID, P.GENERATION + 1
    FROM ECOLI_DATA AS C
    JOIN GENERATIONS AS P ON C.PARENT_ID = P.ID
)
SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GENERATIONS AS G
LEFT JOIN ECOLI_DATA AS C ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;