-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT D.ID
    FROM DEVELOPERS AS D
    JOIN SKILLCODES AS S ON (D.SKILL_CODE & S.CODE) = S.CODE
    WHERE S.CATEGORY = 'Front End'
)
ORDER BY ID;